# Configuración para Cloudflare Pages
name = "walletfy-llm"
compatibility_date = "2024-11-01"

# Para Cloudflare Pages - configuración específica
pages_build_output_dir = "dist"

# Variables de entorno (puedes agregar más aquí)
[vars]
NODE_ENV = "production"
