/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as IndexImport } from './routes/index'
import { Route as FormEventFormImport } from './routes/form/event-form'
import { Route as FormIdNewImport } from './routes/form/$id-new'
import { Route as FormIdImport } from './routes/form/$id'

// Create/Update Routes

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const FormEventFormRoute = FormEventFormImport.update({
  id: '/form/event-form',
  path: '/form/event-form',
  getParentRoute: () => rootRoute,
} as any)

const FormIdNewRoute = FormIdNewImport.update({
  id: '/form/$id-new',
  path: '/form/$id-new',
  getParentRoute: () => rootRoute,
} as any)

const FormIdRoute = FormIdImport.update({
  id: '/form/$id',
  path: '/form/$id',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/form/$id': {
      id: '/form/$id'
      path: '/form/$id'
      fullPath: '/form/$id'
      preLoaderRoute: typeof FormIdImport
      parentRoute: typeof rootRoute
    }
    '/form/$id-new': {
      id: '/form/$id-new'
      path: '/form/$id-new'
      fullPath: '/form/$id-new'
      preLoaderRoute: typeof FormIdNewImport
      parentRoute: typeof rootRoute
    }
    '/form/event-form': {
      id: '/form/event-form'
      path: '/form/event-form'
      fullPath: '/form/event-form'
      preLoaderRoute: typeof FormEventFormImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/form/$id': typeof FormIdRoute
  '/form/$id-new': typeof FormIdNewRoute
  '/form/event-form': typeof FormEventFormRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/form/$id': typeof FormIdRoute
  '/form/$id-new': typeof FormIdNewRoute
  '/form/event-form': typeof FormEventFormRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/form/$id': typeof FormIdRoute
  '/form/$id-new': typeof FormIdNewRoute
  '/form/event-form': typeof FormEventFormRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/form/$id' | '/form/$id-new' | '/form/event-form'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/form/$id' | '/form/$id-new' | '/form/event-form'
  id: '__root__' | '/' | '/form/$id' | '/form/$id-new' | '/form/event-form'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  FormIdRoute: typeof FormIdRoute
  FormIdNewRoute: typeof FormIdNewRoute
  FormEventFormRoute: typeof FormEventFormRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  FormIdRoute: FormIdRoute,
  FormIdNewRoute: FormIdNewRoute,
  FormEventFormRoute: FormEventFormRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/form/$id",
        "/form/$id-new",
        "/form/event-form"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/form/$id": {
      "filePath": "form/$id.tsx"
    },
    "/form/$id-new": {
      "filePath": "form/$id-new.tsx"
    },
    "/form/event-form": {
      "filePath": "form/event-form.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
